### ISSUE TITLE
Uploads returning FileTitle as null

### ISSUE THREAD

**Issue by kdraper** [ADefWebserver/Blazor-Blogs#38]
In your Blazor-Blogs website I needed to do the following changes to get Uploads to work
1) Create wwwroot/files
2) add the following code change to upload controller
if (FileTitle == null )
{
FileTitle = "[Unknown]";
}

**Comment by ADefWebserver** [comment]
Can I ask how and where you installed Blazor-Blogs (for example did you download the install .zip from the releases page and install it on Azure)? 

Also, what web browser you used?

Thanks!

**Comment by kdraper** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  1) downloaded blazorblogslibrary from github2) created BlazorBlogs database on local ms SQL server20173) compiled and ran BlazorBlogsLibrary.csproj4) used your install  screen to setup database in step 25) created adnin user etc6) running locally on chrome not in AzureKeb                                                                                                                                             Sent via BlackBerry Hub+ Inbox for Android                                                                                                                                                                           From: notifications@github.comSent: May 19, 2020 11:52 a.m.To: Blazor-Blogs@noreply.github.comReply to: reply@reply.github.comCc: kdraper@rogers.com; author@noreply.github.comSubject: Re: [ADefWebserver/Blazor-Blogs] Uploads returning FileTitle as null (#38)  
Can I ask how and where you installed Blazor-Blogs (for example did you download the install .zip from the releases page and install it on Azure)?
Also, what web browser you used?
Thanks!

**Comment by ADefWebserver** [comment]
Can you please try using the release from:
https://github.com/ADefWebserver/Blazor-Blogs/releases

Thanks!
