### ISSUE TITLE
How would this Blazor Blog Handle SEO meta tags?

### ISSUE THREAD

**Issue by herorelative** [ADefWebserver/Blazor-Blogs#48]
I was digging through and cannot find any solution.

I mean specifically on client-side Blazor not server-side.

**Comment by ADefWebserver** [comment]
This project is of course Sever Side Blazor and *will not* work as Client Side Blazor.

In this page:
https://github.com/ADefWebserver/Blazor-Blogs/blob/main/BlazorBlogsLibrary/Pages/ViewBlogPost.razor

We are using [Toolbelt.Blazor.HeadElement.MetaElement](https://github.com/jsakamoto/Toolbelt.Blazor.HeadElement) to set the meta tags for the page.

**Comment by herorelative** [comment]
Thank you @ADefWebserver  

It helps me a lot.
