### ISSUE TITLE
Where does BlazorBlogsLibrary.Views.dll come from?

### ISSUE THREAD

**Issue by DanielSpindler83** [ADefWebserver/Blazor-Blogs#57]
Hello,

Apologies if this is a silly noob question, but where does the file BlazorBlogsLibrary.Views.dll come from?
It does not seem to be a build output and yet is referenced in BlazorBlogsLibrary.csproj to copy the file after the build of that project.

What am I missing?

Thanks,

Daniel

**Comment by DanielSpindler83** [comment]
I think this may be related to these issues...maybe...?
[https://github.com/dotnet/aspnetcore/issues/28190](https://github.com/dotnet/aspnetcore/issues/28190)
[https://github.com/dotnet/aspnetcore/issues/27888](https://github.com/dotnet/aspnetcore/issues/27888)

**Comment by ADefWebserver** [comment]
> where does the file BlazorBlogsLibrary.Views.dll come from?

It comes from the https://github.com/ADefWebserver/Blazor-Blogs/tree/main/BlazorBlogsLibrary project. The .dlls from that project are put into the "BlazorBlogs/CustomModules" directory of the https://github.com/ADefWebserver/Blazor-Blogs/tree/main/BlazorBlogs project.

You just need to do a "rebuild all" to get it all to build properly.

**Comment by DanielSpindler83** [comment]
Sorry, forgot to mention that I was trying to move to .NET6. 
Issue is that .NET 6 build of BlazorBlogsLibrary.csproj does not output BlazorBlogsLibrary.Views.dll .
I tried cleaning it up to run without that reference, but now stuck with:
InvalidOperationException: Cannot find the fallback endpoint specified by route values: { page: /_Host, area: }.

**Comment by DanielSpindler83** [comment]
Sorry - never mind I think I got it working.
I may drop a PR for the .NET 6 upgrade.
Thanks

**Comment by ADefWebserver** [comment]
> Sorry - never mind I think I got it working. I may drop a PR for the .NET 6 upgrade. Thanks

Thanks for your assistance. However, I plan to upgrade to .Net 7 and do some major refactoring in January.
