### ISSUE TITLE
Blog Post 55 - AzureAdB2C / AzureAd Configuration String Mismatch

### ISSUE THREAD

**Issue by iskarconsulting** [ADefWebserver/Blazor-Blogs#60]
In Blog Post 55 (Creating a Blazor Server Azure B2C App) there is a mismatch between the configuration string in the `appsetting.json` file and the `Program.cs` file.

appsettings.json:
`"AzureAd"`

Program.cs:
`builder.Configuration.Bind("AzureAdB2C", options);`

**Comment by ADefWebserver** [comment]
The sample code was correct. The error was in the blog post. This has now been fixed. Thank You.

**Comment by iskarconsulting** [comment]
Thanks for the great blog. It would have taken me weeks figuring out how to do this stuff using the MS docs.
